import Head from "next/head";
import Link from "next/link";
import { compareDesc, format, parseISO } from "date-fns";
import { allPosts } from "/.contentlayer/generated";
import Page from "../components/Page";

export async function getStaticProps() {
  const posts = allPosts.sort((a, b) => {
    return compareDesc(new Date(a.date), new Date(b.date));
  });
  return { props: { posts } };
}

function PostCard(post) {
  return (
    <div className="mb-6">
      <time dateTime={post.date}>
        {format(parseISO(post.date), "LLLL d, yyyy")}
      </time>
      <h2 className="text-lg">
        <Link href={post.url}>{post.title}</Link>
      </h2>
    </div>
  );
}

export default function Home({ posts }) {
  return (
    <Page>
      <Head>
        <title>Blog of sheenski</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {posts.map((post, idx) => (
          <PostCard key={idx} {...post} />
        ))}
      </main>
    </Page>
  );
}
