import Head from "next/head";
import Link from "next/link";
import { compareDesc } from "date-fns";
import { allPosts } from "/.contentlayer/generated";
import Page from "../components/Page";
import FormattedDate from "../components/Date";
import { Text, Divider } from "@mantine/core";

export async function getStaticProps() {
  const posts = allPosts.sort((a, b) => {
    return compareDesc(new Date(a.date), new Date(b.date));
  });
  return { props: { posts } };
}

function PostCard(post) {
  return (
    <div className="mb-6">
      <Text fz="xl">
        <Link href={post.url}>{post.title}</Link>
      </Text>
      <Text mt="sm">{post.blurb}</Text>
      <Text c="dimmed" mt="sm">
        <FormattedDate date={post.date} />
      </Text>
      <Divider mt="md" mb="md" />
    </div>
  );
}

export default function Home({ posts }) {
  return (
    <Page title="Blog a la Sheenski - Index">
      <Head>
        <title>Blog of sheenski</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {posts.map((post, index) => (
          <PostCard key={index} {...post} />
        ))}
      </main>
    </Page>
  );
}
